name: Deploy to the production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 195.35.20.53
          username: root
          password: Binarydata@7
          script: |
            [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
            cd /var/www/smart-exams
            git add .
            git commit -m "merge previous changes"
            git pull origin main
            npm run setup
            npm run build
            if [ $? -eq 0 ]; then
                # Restart PM2
                pm2 reload smart-exams
            else
                echo "Error: Build failed. Stopping PM2."
                exit 1
            fi
